In [1]:
#Opening an image,printing its shape and converting into grayscale

#import numpy and open-cv
import numpy as np
import cv2 
from matplotlib import pyplot as plt

#Read the image into img
img = cv2.imread('prajin.jpg')


#display image
cv2.imshow('pic',img)

#Change picture into grayscale and display it
img1 = cv2.imread('pic.jpg',0)
cv2.imshow('GrayPic',img1)

#display image indefinitely until closed
cv2.waitKey(0)

#clear windows
cv2.destroyAllWindows()

#shape returns a tuple of the number of rows, columns, and channels (if the image is color)
print(img.shape)

print(img[:,:,0])

(200, 200, 3)
[[117 115 111 ...   3   0   4]
 [127 122 115 ...   7   3   3]
 [135 127 120 ...   6   8   8]
 ...
 [143 143 144 ... 218 236 237]
 [143 140 144 ... 205 232 242]
 [147 141 145 ... 178 215 239]]
